# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build test

on:
  pull_request:
    branches: [ development ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Lint using ESLint
      run: npm run lint --if-present
#   - name: Test
#     run: npm run test
    - name: Build Gatsby site
      run: npm run build --if-present
